webtalk_init -webtalk_dir C:/Users/wind/Desktop/Master_Thesis/Text_and_hardware/Hardware/Secure_Control/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/paillier_inverted_pendulum_tben_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 21 03:28:40 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a6fbf037-e711-46d7-b80e-495403f28cbc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6eba2e4c5a2a4fedadf174e188706abe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "21.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7016_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3219243189 -regid "" -xml C:/Users/wind/Desktop/Master_Thesis/Text_and_hardware/Hardware/Secure_Control/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/paillier_inverted_pendulum_tben_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/wind/Desktop/Master_Thesis/Text_and_hardware/Hardware/Secure_Control/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/paillier_inverted_pendulum_tben_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/wind/Desktop/Master_Thesis/Text_and_hardware/Hardware/Secure_Control/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/paillier_inverted_pendulum_tben_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
